Nutriologo/Controllers/ConsultaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Nutriologo.Models;

namespace Nutriologo.Controllers
{
    public class ConsultaController : Controller
    {

        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        ApplicationUser usuario;

        public ConsultaController(ApplicationDbContext context, UserManager<ApplicationUser> userManager, RoleManager<IdentityRole> roleManager)
        {
            _context = context;
            _userManager = userManager;
            _roleManager = roleManager;
        }

        // GET: Consulta
        public async Task<IActionResult> Index()
        {
            usuario = await _userManager.FindByEmailAsync(User.Identity.Name);
            List<Consulta> consultas = await(from co in _context.Consultas
                                             where co.FacturaDisponible == true && co.Correo == usuario.Email
                                            select co
                                            ).ToListAsync();

            return View(consultas);
        }

        // GET: Consulta/Create
        public async Task<IActionResult> Registrar(string correo, DateTime hora)
        {

            Cita cita = await (from ci in _context.Citas
                                 where ci.Email == correo && ci.Hora == hora
                                select ci
                                ).FirstOrDefaultAsync();

            Consulta consulta = new Consulta();

            cita.FueConsultada = true;
            consulta.Correo = cita.Email;
            consulta.Fecha = cita.Fecha;
            consulta.FacturaDisponible = true;
            consulta.IdCita = cita.Id;

            _context.Update(cita);
            await _context.SaveChangesAsync();

            return View(consulta);
        }

        // POST: Consulta/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Registrar(IFormCollection collection)
        {
            try
            {

                Consulta consulta = new Consulta();
                consulta.Correo = collection["Correo"];
                consulta.Costo = float.Parse(collection["Costo"]);
                consulta.FacturaDisponible = true;
                consulta.Fecha = DateTime.Parse(collection["Fecha"]);
                consulta.Peso = float.Parse(collection["Peso"]);
                consulta.Talla = float.Parse(collection["Talla"]);
                consulta.IdCita = int.Parse(collection["IdCita"]);

                _context.Consultas.Add(consulta);

                _context.SaveChanges();

                return RedirectToAction("Ver", "Citas");
            }
            catch
            {
                return View();
            }
        }

        // GET: Consulta/Edit/5
        public ActionResult Editar(int id)
        {
            return View();
        }

        // POST: Consulta/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Editar(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Consulta/Delete/5
        public ActionResult Eliminar(int id)
        {
            return View();
        }

        // POST: Consulta/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Eliminar(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Nutriologo/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace Nutriologo.Controllers
{
    [Authorize]
    public class DashboardController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ApplicationDbContext _context;
        ApplicationUser usuario;

        public DashboardController(UserManager<ApplicationUser> userManager, ApplicationDbContext context)
        {
            _userManager = userManager;
            _context = context;
        }

        // GET: Dashboard
        public async Task<ActionResult> Consultar()
        {
            usuario = await _userManager.FindByEmailAsync(User.Identity.Name);
            if(usuario.IdDatosPrivados == 0)
            {
                return RedirectToAction("CompletarRegistro", "Account");
            }
            var consultas = _context.Consultas.Where(c => c.Correo == usuario.Email).ToList();
            return View(consultas);
        }

        // GET: Dashboard/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Dashboard/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Dashboard/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction(nameof(Consultar));
            }
            catch
            {
                return View();
            }
        }

        // GET: Dashboard/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Dashboard/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Consultar));
            }
            catch
            {
                return View();
            }
        }

        // GET: Dashboard/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Dashboard/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Consultar));
            }
            catch
            {
                return View();
            }
        }
    }
}

Nutriologo/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> SignInManager

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Nutriologo</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE=" />
    </environment>

    <script src="~/lib/jquery/dist/jquery.js"></script>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Nutriologo</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    @if (User.IsInRole("Admin") || User.IsInRole("Usuario"))
    {
        <div class="container-fluid">
            <partial name="_CookieConsentPartial" />
            <div class="row">
                <div class="col-3">
                    <div class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
                        @if (User.IsInRole("Admin"))
                        {
                            <a class="nav-link" id="_Citas_Ver" asp-action="Ver" asp-controller="Citas" aria-controls="v-pills-messages" aria-selected="false">Ver Citas</a>
                            <a class="nav-link" id="_Account_VerUsuarios" asp-action="VerUsuarios" asp-controller="Account" aria-controls="v-pills-profile" aria-selected="false">Ver usuarios</a>


                        }
                        else
                        {
                            <a class="nav-link active" id="_Dashboard_Consultar" asp-action="Consultar" asp-controller="Dashboard" aria-selected="true">Mi Nutrición</a>
                            <a class="nav-link" id="_Citas_Registrar" asp-action="Registrar" asp-controller="Citas" aria-controls="v-pills-profile" aria-selected="false">Agendar Cita</a>
                            <a class="nav-link" id="_Citas_Ver" asp-action="Ver" asp-controller="Citas" aria-controls="v-pills-messages" aria-selected="false">Mis citas</a>
                            <a class="nav-link" id="_Citas_Facturar" asp-action="Index" asp-controller="Consulta" aria-controls="v-pills-messages" aria-selected="false">Citas Por Facturar</a>

                        }
                        <a class="nav-link" id="_Account_CompletarRegistro" asp-action="CompletarRegistro" asp-controller="Account" aria-controls="v-pills-settings" aria-selected="false">Modificar Datos Privados</a>
                    </div>
                </div>
                <div class="col-9">
                    @RenderBody()
                </div>
            </div>
        </div>
    }
    else
    {
        <div class="container">
            @RenderBody()
        </div>
        
    }


    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - Nutriologo - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/Layout.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>